# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z9byPMzrrblqrmqO4d-_xA6NyG2o6IE3
"""

import streamlit as st
import random

st.set_page_config(layout="wide")
st.title('Test Streamlit')

st.write('Hello World!')

st.sidebar.title('Filter')
st.sidebar.header('Option')
st.sidebar.selectbox(
    "Pls Select One!",
    ('opt1', 'opt2', 'opt3')
)

with st.sidebar:
    st.radio(
        "Pls Choose One!",
        ['cho1', 'cho2', 'cho3'],
    )