# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z9byPMzrrblqrmqO4d-_xA6NyG2o6IE3
"""

import streamlit as st
import pandas as pd

df = pd.DataFrame(
    {
        "first column": [1, 2, 3, 4],
        "second column": [10, 20, 30, 40]
    }
)

st.set_page_config(layout="wide")
st.title('Test Streamlit')

st.write('Hello World!')

st.write("1 + 1 = ", 2)

st.write(df)